@startuml
namespace config {
    class Config << (S,Aquamarine) >> {
        + Server ServerConfig
        + Database DatabaseConfig
        + Security SecurityConfig
        + Defaults DefaultConfig
        + Logging LoggingConfig
        + RateLimit RateLimitConfig

    }
    class DatabaseConfig << (S,Aquamarine) >> {
        + Host string
        + Port int
        + User string
        + Password string
        + Name string
        + SSLMode string
        + MaxIdleConns int
        + MaxOpenConns int
        + ConnMaxLifetime time.Duration
        + MigrationEnabled bool

    }
    class DefaultConfig << (S,Aquamarine) >> {
        + Provider string
        + Model string
        + Providers []ProviderConfig

    }
    class LoggingConfig << (S,Aquamarine) >> {
        + Level string
        + Format string

    }
    class ModelConfig << (S,Aquamarine) >> {
        + Name string
        + Parameters string
        + Config string
        + ResponsePath string

    }
    class ProviderConfig << (S,Aquamarine) >> {
        + Name string
        + BaseURL string
        + APIKey string
        + Default bool
        + Models []ModelConfig
        + AuthMethod string

    }
    class RateLimitConfig << (S,Aquamarine) >> {
        + Enabled bool
        + Requests float64
        + Window string
        + IPWhitelist []string

    }
    class SecurityConfig << (S,Aquamarine) >> {
        + EncryptionKey string
        + EncryptionKeyVersion int

    }
    class ServerConfig << (S,Aquamarine) >> {
        + Port int
        + ReadTimeout time.Duration
        + WriteTimeout time.Duration
        + IdleTimeout time.Duration

    }
}


namespace controller {
    class SystemPromptController << (S,Aquamarine) >> {
        - svc *service.SystemPromptService

        + Create(ctx *gin.Context) 
        + Get(ctx *gin.Context) 
        + Update(ctx *gin.Context) 
        + Delete(ctx *gin.Context) 
        + Send(ctx *gin.Context) 

    }
}


namespace database {
    class Config << (S,Aquamarine) >> {
        + Host string
        + Port int
        + User string
        + Password string
        + DBName string
        + SSLMode string

    }
}


namespace models {
    class AIUsageLog << (S,Aquamarine) >> {
        + ID uuid.UUID
        + ModuleName string
        + Provider string
        + PromptHash string
        + Request string
        + Response string
        + UsedAt time.Time

    }
    class RateLimit << (S,Aquamarine) >> {
        + ID uuid.UUID
        + ModuleName string
        + Provider string
        + MaxRequests int
        + PerSeconds int

    }
    class SystemPrompt << (S,Aquamarine) >> {
        + ID uuid.UUID
        + ModuleName string
        + ModelName string
        + Provider string
        + SystemPrompt string
        + CreatedAt time.Time
        + UpdatedAt time.Time
        + DeletedAt gorm.DeletedAt

    }
}


namespace repository {
    class SystemPromptRepo << (S,Aquamarine) >> {
        - db *gorm.DB

        + WithTransaction(ctx context.Context, fn <font color=blue>func</font>(context.Context) error) error
        + Create(ctx context.Context, sp *model.SystemPrompt) error
        + GetByHash(ctx context.Context, hash string) (*model.SystemPrompt, error)
        + Update(ctx context.Context, sp *model.SystemPrompt) error
        + Delete(ctx context.Context, id string) error
        + List(ctx context.Context) ([]model.SystemPrompt, error)

    }
    class repository.contextKey << (T, #FF7700) >>  {
    }
}


namespace service {
    class SystemPromptService << (S,Aquamarine) >> {
        - repo *repository.SystemPromptRepo
        - db *gorm.DB
        - cfg *config.Config

        - getActiveProviderAndModel() (*config.ProviderConfig, *config.ModelConfig, error)
        - getCachedResponse(ctx context.Context, hash string) (*model.AIUsageLog, error)
        - checkRateLimit(ctx context.Context, module string, provider string) error
        - callAIAPI(ctx context.Context, provider *config.ProviderConfig, model *config.ModelConfig, sys string, user string) (string, error)
        - extractResponse(body []byte, path string) (string, error)

        + Create(ctx context.Context, module string, provider string, sys string, modelname string) (*model.SystemPrompt, error)
        + Get(ctx context.Context) ([]model.SystemPrompt, error)
        + GetHash(ctx context.Context, hash string) (*model.SystemPrompt, error)
        + Update(ctx context.Context, id string, sys string, user string) error
        + Delete(ctx context.Context, id string) error
        + SendPrompt(ctx context.Context, module string, sys string, user string, bypassCache bool) (*model.AIUsageLog, error)

    }
}


"__builtin__.string" #.. "repository.contextKey"
@enduml
