services:
  ai-service:
    build: ./ai-service/
    ports:
      - "8082:8080"
    volumes:
      - ./ai-service:/app
    env_file:
      - ./ai-service/.env
    depends_on:
      - db
    networks:
      - app-network

  ai-database:
    image: postgres:latest
    restart: always
    env_file:
      - ./ai-service/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
