// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/provider_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/provider_service.go -destination=internal/service/mocks/mock_provider_service.go
//

// Package mock_service is a generated GoMock package.
package mock_service
