server:
  port: 8080
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s

database:
  host: postgres
  port: 5432
  user: admin
  password: secret
  name: providers
  ssl_mode: disable
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h
  migration_enabled: true 

security:
  encryption_key: "UHROnUj/LjVL+x+jpMc/0HQWSc7f0YDh"
  encryption_key_version: 1

defaults:
  provider: "gemini"
  model: "gemini-2.0-flash"
  providers:
    - name: "gemini"
      base_url: "https://generativelanguage.googleapis.com/v1beta/models/"
      api_key: "${GEMINI_API_KEY}"
      auth_method: "query_param"
      models:
        - name: "gemini-2.0-flash"
          parameters: '{"temperature": 0.9, "maxOutputTokens": 100}'
          config: |
            {
              "contents": [{
                "parts": [
                  {"text": "{{.SystemPrompt}}"},
                  {"text": "{{.UserPrompt}}"}
                ]
              }]
            }
          response_path: "candidates.0.content.parts.0.text"

logging:
  level: info
  format: json

rate_limit:
  enabled: true
  requests: 100
  window: "1m"
  ip_whitelist:
    - "127.0.0.1"
